### ISSUE TITLE
Model Config.yaml in Docker Container and Error Catching

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai-api#13]
I was trying to run the API with just CTransformers so I filled out the config.yaml as shown by the config-example.yaml. When I went to run the docker containers, the API could not figure out where/what CTransformers was leading to an uncaught error on the backend. The fix is 2-fold:

1. Catch errors gracefully when an unknown model is requested.
2. Add instructions or a line in the Dockerfile to copy over config.yaml (if exists) as written by the user

The addition of `COPY config.yaml .` in the Docker file fixed my problem.

Without the config.yaml, the errors were not caught properly.

**Comment by YrrepNoj** [comment]
1. is a good point, we should be more graceful with error handling.

2. I strongly disagree with, I do not think we should be including the configuration in the Dockerfile itself. Including the `config.yaml` in the Dockerfile means that we have are building a distinctly new image for each deployment. This is because each deployment environment will have a different combination of models located in their own unique `backend` locations. 

This is a [service discovery](https://www.nginx.com/blog/service-discovery-in-a-microservices-architecture/) issue that should be handled by the environment/greater-system and not the container itself.

One solution I'd rather we explore is expanding upon the [docker-compose](https://github.com/defenseunicorns/leapfrogai/blob/main/compose/docker-compose.yaml) that got introduced and using volumes to point the API to the correct config (with the help from env vars where needed).

**Comment by gerred** [comment]
Agreed. This is some of the pain of distributed systems - there's not a hermetically sealed unit here when there is a dependency across a network barrier. This repo should not include a config.yaml in it's Dokcer images by default just because it is a distsys and it's crossing a boundary into another system.

@justinthelaw I'd agree if this were a completely single unit, but it's not here, so in-and-of-itself it's not something a Dockerfile can fix when a base, complete, deployable unit would have to be a compose file / helm chart / Zarf package /etc.

**Comment by YrrepNoj** [comment]
Also slightly useful to note that this gets handled within k8s thanks to the `kiwigrid` sidecar. The sidecar watches for updates to secrets & configmaps with a specific label and then writes configs to a location that the api pod is reading configs from.

**Comment by justinthelaw** [comment]
For local development, where I am trying to integrate a backend to the API, it is not possible using docker without the config.yaml. The API is unable to discover the backend across the host network (localhost) so i have to copy over and include the config.yaml in the Dockerbuild. I mean, it's okay if we decide not to keep that in the code base, but the problem is that we'll need local developers running a different backend at a different domain/address/port to manually add `COPY config.yaml .`

Once we solidify the API more, we'll want to make README instructions caveating local docker build/run, versus docker-compose of diff/multiple services, versus k8s deployment.
